### PR TITLE
fix marina leak

### PR DESCRIPTION
**Pull request by anderswei**

### CODE REVIEW

**Review by TT-lwang — APPROVED** [review]

**Review by TT-jHao — APPROVED** [review]

**Comment by anderswei** [comment]
testing in progress

**Review by nitzanharel — APPROVED** [review]
probably a good enough implementation (last famous words) until we address it thoroughly

**Comment by anderswei** [comment]
```erlang
F = fun() -> V = lists:filter(
     fun(Port) ->
	     case erlang:port_info(Port, name) of
		  {name, "tcp_inet"} -> true;
		  _ -> false
	     end
     end, erlang:ports()), 

X = lists:filtermap(fun(S) -> 
    case  prim_inet:peername(S) of 
    {ok,{Addr,9042}} -> 
{true, Addr} ; 
    _ -> false 
    end 
end, V), 
{lists:usort(X), length(X)}
end. 
```

**Comment by anderswei** [comment]
before
image
image

you can see there is a leak for remote port 9042. 

After this PR:
 no leak any more locally: 
```
(ttserver@localhost)16> F(). 
{[{127,0,0,1}],26}
(ttserver@localhost)17> 
(ttserver@localhost)17> F(). 
{[{127,0,0,1}],26}
(ttserver@localhost)18> 
(ttserver@localhost)18> F(). 
{[{127,0,0,1}],26}
```

**Pull request merged**
